//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundPackCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal localization() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundPackCreator.Properties.localization", typeof(localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured during the installation..
        /// </summary>
        public static string dialog_error_install_default_error_occured_message {
            get {
                return ResourceManager.GetString("dialog_error_install_default_error-occured_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default pack installation error.
        /// </summary>
        public static string dialog_error_install_default_error_occured_title {
            get {
                return ResourceManager.GetString("dialog_error_install_default_error-occured_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The soundpack doesn&apos;t exists..
        /// </summary>
        public static string dialog_error_install_pack_not_exists_message {
            get {
                return ResourceManager.GetString("dialog_error_install_pack-not-exists_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installation error.
        /// </summary>
        public static string dialog_error_install_pack_not_exists_title {
            get {
                return ResourceManager.GetString("dialog_error_install_pack-not-exists_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The pack file selected is corrupted or incorrect..
        /// </summary>
        public static string dialog_error_open_selected_pack_corrupted_message {
            get {
                return ResourceManager.GetString("dialog_error_open_selected-pack-corrupted_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open pack error.
        /// </summary>
        public static string dialog_error_open_selected_pack_corrupted_title {
            get {
                return ResourceManager.GetString("dialog_error_open_selected-pack-corrupted_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The pack file selected doesn&apos;t exists..
        /// </summary>
        public static string dialog_error_open_selected_pack_not_exists_message {
            get {
                return ResourceManager.GetString("dialog_error_open_selected-pack-not-exists_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open pack error.
        /// </summary>
        public static string dialog_error_open_selected_pack_not_exists_title {
            get {
                return ResourceManager.GetString("dialog_error_open_selected-pack-not-exists_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured during the save.
        ///Please try to change the path of the file or execute this application with admin rights..
        /// </summary>
        public static string dialog_error_save_message {
            get {
                return ResourceManager.GetString("dialog_error_save_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save error.
        /// </summary>
        public static string dialog_error_save_title {
            get {
                return ResourceManager.GetString("dialog_error_save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The folder where you selected the exe file doesn&apos;t contains audio folder of the game.
        /// </summary>
        public static string dialog_error_select_game_folder_not_exists_message {
            get {
                return ResourceManager.GetString("dialog_error_select_game_folder-not-exists_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open game error.
        /// </summary>
        public static string dialog_error_select_game_folder_not_exists_title {
            get {
                return ResourceManager.GetString("dialog_error_select_game_folder-not-exists_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WARNING: If you press yes, your game will restart !
        ///Do you want to install the soundpack on this game :
        ///
        ///Location :
        ///.
        /// </summary>
        public static string dialog_question_select_game_message {
            get {
                return ResourceManager.GetString("dialog_question_select-game_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select this game ?.
        /// </summary>
        public static string dialog_question_select_game_title {
            get {
                return ResourceManager.GetString("dialog_question_select-game_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save the soundpack.
        /// </summary>
        public static string dialog_select_save_pack_title {
            get {
                return ResourceManager.GetString("dialog_select_save-pack_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To install this current soundpack, you need to save it before..
        /// </summary>
        public static string dialog_warning_install_need_save_before_message1 {
            get {
                return ResourceManager.GetString("dialog_warning_install_need-save-before_message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save before.
        /// </summary>
        public static string dialog_warning_install_need_save_before_title1 {
            get {
                return ResourceManager.GetString("dialog_warning_install_need-save-before_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The current sound pack is not saved, do you want to save it now ?.
        /// </summary>
        public static string dialog_warning_pack_not_saved_message1 {
            get {
                return ResourceManager.GetString("dialog_warning_pack-not-saved_message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save the soundpack.
        /// </summary>
        public static string dialog_warning_pack_not_saved_title1 {
            get {
                return ResourceManager.GetString("dialog_warning_pack-not-saved_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select.
        /// </summary>
        public static string ui_button_detect_game_select {
            get {
                return ResourceManager.GetString("ui_button_detect-game_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        public static string ui_label_author {
            get {
                return ResourceManager.GetString("ui_label_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A special thanks to Trabuco and Princess Mae
        ///for the correction of the Spanish and English translations !
        ///
        ///Thanks to the entire DDraceNetwork community !.
        /// </summary>
        public static string ui_label_credits_message {
            get {
                return ResourceManager.GetString("ui_label_credits_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string ui_label_description {
            get {
                return ResourceManager.GetString("ui_label_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, launch your game, it will be automatically detected.
        ///If your game is not detected, click on the button &quot;Select&quot;
        ///then select the &quot;.exe&quot; file of your game..
        /// </summary>
        public static string ui_label_detect_game_select {
            get {
                return ResourceManager.GetString("ui_label_detect-game_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pack informations.
        /// </summary>
        public static string ui_label_informations {
            get {
                return ResourceManager.GetString("ui_label_informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The replacement.
        /// </summary>
        public static string ui_label_new_sound {
            get {
                return ResourceManager.GetString("ui_label_new-sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        public static string ui_menu_file {
            get {
                return ResourceManager.GetString("ui_menu_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        public static string ui_menu_file_new {
            get {
                return ResourceManager.GetString("ui_menu_file_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        public static string ui_menu_file_open {
            get {
                return ResourceManager.GetString("ui_menu_file_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string ui_menu_file_quit {
            get {
                return ResourceManager.GetString("ui_menu_file_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string ui_menu_file_save {
            get {
                return ResourceManager.GetString("ui_menu_file_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save as.
        /// </summary>
        public static string ui_menu_file_save_as {
            get {
                return ResourceManager.GetString("ui_menu_file_save-as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        public static string ui_menu_help {
            get {
                return ResourceManager.GetString("ui_menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Credits.
        /// </summary>
        public static string ui_menu_help_credits {
            get {
                return ResourceManager.GetString("ui_menu_help_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install.
        /// </summary>
        public static string ui_menu_install {
            get {
                return ResourceManager.GetString("ui_menu_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install current.
        /// </summary>
        public static string ui_menu_install_current {
            get {
                return ResourceManager.GetString("ui_menu_install-current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restore default.
        /// </summary>
        public static string ui_menu_install_default {
            get {
                return ResourceManager.GetString("ui_menu_install-default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open and install.
        /// </summary>
        public static string ui_menu_install_open_install {
            get {
                return ResourceManager.GetString("ui_menu_install_open-install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove this sound from the soundpack.
        /// </summary>
        public static string ui_tooltip_button_delete_sound {
            get {
                return ResourceManager.GetString("ui_tooltip_button_delete-sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Listen to your beautiful sound.
        /// </summary>
        public static string ui_tooltip_button_play_sound {
            get {
                return ResourceManager.GetString("ui_tooltip_button_play-sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a sound file from your storage.
        /// </summary>
        public static string ui_tooltip_button_select_sound {
            get {
                return ResourceManager.GetString("ui_tooltip_button_select-sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new soundpack, will reset everything.
        /// </summary>
        public static string ui_tooltip_menu_file_new {
            get {
                return ResourceManager.GetString("ui_tooltip_menu_file_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open a soundpack from your storage.
        /// </summary>
        public static string ui_tooltip_menu_file_open {
            get {
                return ResourceManager.GetString("ui_tooltip_menu_file_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit this application, or you can click on the red cross, as you want.
        /// </summary>
        public static string ui_tooltip_menu_file_quit {
            get {
                return ResourceManager.GetString("ui_tooltip_menu_file_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save the current soundpack.
        /// </summary>
        public static string ui_tooltip_menu_file_save {
            get {
                return ResourceManager.GetString("ui_tooltip_menu_file_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save the current soundpack in a new specific file.
        /// </summary>
        public static string ui_tooltip_menu_file_save_as {
            get {
                return ResourceManager.GetString("ui_tooltip_menu_file_save-as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install.
        /// </summary>
        public static string ui_tooltip_menu_install {
            get {
                return ResourceManager.GetString("ui_tooltip_menu_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install the soundpack currently open in your game.
        /// </summary>
        public static string ui_tooltip_menu_install_current {
            get {
                return ResourceManager.GetString("ui_tooltip_menu_install-current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restore the default soundpack of the game.
        /// </summary>
        public static string ui_tooltip_menu_install_default {
            get {
                return ResourceManager.GetString("ui_tooltip_menu_install-default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open a soundpack from your storage and install it.
        /// </summary>
        public static string ui_tooltip_menu_install_open_install {
            get {
                return ResourceManager.GetString("ui_tooltip_menu_install_open-install", resourceCulture);
            }
        }
    }
}
